import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ModulePage } from "../layout/ModulePage";
import { useCassLabStore, rowKeyString } from "../../state/store";
import type { ColumnDefinition, RowValue } from "../../domain/types";

function isAutoGenerated(col: ColumnDefinition): boolean {
  return col.type === "uuid" || col.type === "timeuuid";
}

function generateAutoValue(): string {
  if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();
  return `${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function inputTypeFor(col: ColumnDefinition): string {
  switch (col.type) {
    case "int":
    case "real":
    case "float":
      return "number";
    case "date":
      return "date";
    case "datetime":
      return "datetime-local";
    case "time":
      return "time";
    case "boolean":
      return "checkbox";
    default:
      return "text";
  }
}

export function InsertionPage() {
  const tables = useCassLabStore((s) => s.tables);
  const cluster = useCassLabStore((s) => s.cluster);
  const activeTableId = useCassLabStore((s) => s.activeTableId);
  const setActiveTableId = useCassLabStore((s) => s.setActiveTableId);
  const insertRow = useCassLabStore((s) => s.insertRow);
  const setActiveRowId = useCassLabStore((s) => s.setActiveRowId);
  const rows = useCassLabStore((s) => s.rows);
  const navigate = useNavigate();

  const activeTable = tables.find((t) => t.id === activeTableId) ?? tables[0];
  const [values, setValues] = useState<Record<string, RowValue>>({});

  useEffect(() => {
    if (!activeTable) return;
    const initial: Record<string, RowValue> = {};
    for (const col of activeTable.columns) {
      initial[col.name] = isAutoGenerated(col) ? generateAutoValue() : "";
    }
    setValues(initial);
  }, [activeTable?.id]);

  if (tables.length === 0) {
    return (
      <ModulePage
        title="Insertion"
        description="Create a table in DDL Analysis first."
        canvas={<p className="hint">No tables yet. Go to the DDL Analysis module to create one.</p>}
        panel={<p className="hint">Nothing to show.</p>}
      />
    );
  }

  const tableRows = rows.filter((r) => r.tableId === activeTable.id && !r.tombstonedAt);

  const handleSubmit = () => {
    if (!cluster) {
      alert("Build a cluster first (Cluster Configuration module).");
      return;
    }
    const row = insertRow(activeTable.id, values);
    setActiveRowId(row.id);
    navigate("/write-path");
  };

  return (
    <ModulePage
      title="Insertion"
      description="Pick a table, fill in its columns, and insert a row. UUID / TimeUUID columns are generated automatically by the simulator. Submitting opens the Write Path animation."
      canvas={
        <div>
          <div className="table-list" style={{ marginBottom: 18 }}>
            {tables.map((t) => (
              <button
                key={t.id}
                type="button"
                className={`table-list-item ${t.id === activeTable.id ? "active" : ""}`}
                onClick={() => setActiveTableId(t.id)}
                style={{ width: "100%", textAlign: "left" }}
              >
                <span>
                  <strong>{t.name}</strong> — {t.columns.length} column(s), {tableRows.length && t.id === activeTable.id ? tableRows.length : rows.filter((r) => r.tableId === t.id && !r.tombstonedAt).length} row(s)
                </span>
                <span className="badge badge-info">PK: {t.primaryKey.join(", ")}</span>
              </button>
            ))}
          </div>

          <h4>Insert into {activeTable.name}</h4>
          {activeTable.columns.map((col) => {
            const auto = isAutoGenerated(col);
            return (
              <div className="field" key={col.name}>
                <label>
                  {col.name} <span className="hint">({col.type})</span>
                  {activeTable.primaryKey.includes(col.name) && <span className="badge badge-info" style={{ marginLeft: 6 }}>key</span>}
                </label>
                {auto ? (
                  <div className="flex-row" style={{ alignItems: "center" }}>
                    <code className="mono">{String(values[col.name] ?? "")}</code>
                    <button
                      className="btn"
                      onClick={() => setValues((v) => ({ ...v, [col.name]: generateAutoValue() }))}
                    >
                      Regenerate
                    </button>
                  </div>
                ) : col.type === "boolean" ? (
                  <input
                    type="checkbox"
                    checked={Boolean(values[col.name])}
                    onChange={(e) => setValues((v) => ({ ...v, [col.name]: e.target.checked }))}
                  />
                ) : (
                  <input
                    type={inputTypeFor(col)}
                    value={String(values[col.name] ?? "")}
                    onChange={(e) =>
                      setValues((v) => ({
                        ...v,
                        [col.name]: col.type === "int" || col.type === "real" || col.type === "float" ? Number(e.target.value) : e.target.value,
                      }))
                    }
                  />
                )}
              </div>
            );
          })}
          <button className="btn btn-primary" onClick={handleSubmit}>
            Insert (Write)
          </button>
        </div>
      }
      panel={
        <div>
          <h4>Rows in {activeTable.name}</h4>
          {tableRows.length === 0 ? (
            <p className="hint">No rows yet.</p>
          ) : (
            <ul className="param-list">
              {tableRows.map((r) => (
                <li key={r.id}>
                  <span>{rowKeyString(activeTable, r)}</span>
                  <strong>{new Date(r.writeTimestamp).toLocaleTimeString()}</strong>
                </li>
              ))}
            </ul>
          )}
        </div>
      }
    />
  );
}
